import { library } from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'

import '../scss/main.scss'

library.add(fas)
library.add(far)
export * from './Toaster'
export * from './Spinner'
export * from './Graph'
export * from './Button'
export * from './Dropdown'
export * from './Icon'
export * from './Image'
export * from './Badge'
export * from './Panel'
export * from './Pill'
export * from './Checkbox'
export * from './Navbar'
export * from './TextField'
export * from './Switch'
export * from './Radio'
export * from './Alert'
export * from './Modal'
export * from './TextInput'
export * from './Select'
export * from './RichText'
export * from './List'
export * from './DateTimePicker'
export * from './VideoPlayer'
export * from './Layout'
export * from './Label'
export * from './Breadcrumb'
export * from './Tab'
export * from './Typeahead'
export * from './Typography'
export * from './Calendar'
export * from './Table'
export * from './Callout'
